
services:
  postgres:
    image: postgres:15
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: apoorv@2025
      POSTGRES_DB: apoorv
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  redis:
    image: redis:latest
    container_name: redis_cache
    restart: always
    ports:
      - "6379:6379"

  server:
    build: 
      context: ./server
      dockerfile: Dockerfile
    container_name: server
    restart: always
    depends_on:
      - postgres
      - redis
    ports:
      - "5000:5000"
    environment:
      DATABASE_URL: "postgres://admin:apoorv%402025@postgres:5432/apoorv"
      JWT_SECRET: '<fFU0z}r0"ebh?)+!.?TollIG[+GHH[_q^{GwhUJ+9RAQcVjGh+X#:)`{Jl_Hsl'
      NODE_ENV: development
    volumes:
      - ./server:/app
      - /app/node_modules

  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    container_name: client
    restart: always
    ports:
      - "5173:5173"
    environment:
      - VITE_API_URL=http://localhost:5000
    volumes:
      - ./client:/app
      - /app/node_modules
    depends_on:
      - server

  admin:
    build:
      context: ./admin
      dockerfile: Dockerfile
    container_name: admin
    restart: always
    ports:
      - "5174:5173"
    environment:
      - VITE_API_URL=http://localhost:5000
    volumes:
      - ./admin:/app
      - /app/node_modules
    depends_on:
      - server

volumes:
  pgdata: