services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: apoorv@2025
    ports:
      - "127.0.0.1:27017:27017"
    volumes:
      - mongodata:/data/db
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.runCommand('ping').ok"]
      interval: 10s
      timeout: 10s
      retries: 5

  mongodb-backup:
    image: mongo:latest
    container_name: mongodb-backup
    restart: always
    depends_on:
      - mongodb
    volumes:
      - ./mongodb_backups:/backups
    entrypoint: >
      /bin/sh -c '
      echo "Waiting for MongoDB to start..."
      sleep 30
      while true; do
        TIMESTAMP=$(date +%Y%m%d_%H%M%S)
        BACKUP_PATH="/backups/backup_$TIMESTAMP"
        echo "Creating backup at $BACKUP_PATH"
        mongodump --host mongodb --port 27017 --authenticationDatabase admin --username admin --password "apoorv@2025" --out $BACKUP_PATH
        
        echo "Compressing backup..."
        cd /backups
        tar -czf "backup_$TIMESTAMP.tar.gz" "backup_$TIMESTAMP"
        rm -rf "backup_$TIMESTAMP"
        
        echo "Cleaning up backups older than 7 days..."
        find /backups -name "backup_*.tar.gz" -type f -mtime +7 -delete
        
        echo "Backup completed at $(date). Next backup in 24 hours."
        sleep 86400
      done
      '
  depends_on:
    mongodb:
      condition: service_healthy

  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: server
    depends_on:
      - mongodb
      # - redis
    ports:
      - "5000:5000"
    environment:
      DATABASE_URL: "mongodb://admin:apoorv%402025@mongodb"
      JWT_SECRET: '<fFU0z}r0"ebh?)+!.?TollIG[+GHH[_q^{GwhUJ+9RAQcVjGh+X#:)`{Jl_Hsl'
      PORT: 5000
      ADMIN_USERNAME: "admin"
      ADMIN_PASSWORD: "admin@apoorv"
      RAZORPAY_KEY_ID: "rzp_live_wm3RAP4PWqiCLd"
      RAZORPAY_KEY_SECRET: "0BUFetF6fAWqWalK0A9WBAus"
      SMTP_SERVICE: "gmail"
      SMTP_USER: "anshumohan22bcy19@iiitkottayam.ac.in"
      SMTP_PASS: "dosp dprv tnfs zuef"
      NODE_ENV: production

  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    container_name: client
    restart: always
    ports:
      - "5173:5173"
    environment:
      - VITE_API_URL=http://server:5000
    depends_on:
      - server

  admin:
    build:
      context: ./admin
      dockerfile: Dockerfile
    container_name: admin
    restart: always
    ports:
      - "5174:5174"
    environment:
      - VITE_API_URL=http://server:5000
    depends_on:
      - server

volumes:
  mongodata:
