services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: apoorv@2025
    ports:
      - "27017:27017"
    volumes:
      - mongodata:/data/db

  redis:
    image: redis:latest
    container_name: redis_cache
    restart: always
    ports:
      - "6379:6379"

  server:
    build: 
      context: ./server
      dockerfile: Dockerfile
    container_name: server
    depends_on:
      - mongodb
      - redis
    ports:
      - "5000:5000"
    environment:
      DATABASE_URL: "mongodb://admin:apoorv%402025@mongodb"
      JWT_SECRET: '<fFU0z}r0"ebh?)+!.?TollIG[+GHH[_q^{GwhUJ+9RAQcVjGh+X#:)`{Jl_Hsl'
      PORT: 5000
      ADMIN_USERNAME: "admin"
      ADMIN_PASSWORD: "admin@apoorv"
      NODE_ENV: development

    develop:
      watch:
        - path: ./server/package.json
          action: rebuild
        - path: ./server/pnpm-lock.yaml
          action: rebuild
        - path: ./server
          target: /app
          action: sync

  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    container_name: client
    restart: always
    ports:
      - "5173:5173"
    environment:
      - VITE_API_URL=http://localhost:5000
    volumes:
      - ./client:/app
      - /app/node_modules
    depends_on:
      - server

  admin:
    build:
      context: ./admin
      dockerfile: Dockerfile
    container_name: admin
    restart: always
    ports:
      - "5174:5173"
    environment:
      - VITE_API_URL=http://localhost:5000
    volumes:
      - ./admin:/app
      - /app/node_modules
    depends_on:
      - server

volumes:
  mongodata:
